### PR TITLE
Add more CS rules

### PR DESCRIPTION
**Pull request by bendem**
Also remove a level of verbosity for travis, we don't really care about the time per file.

The rules are alphabetically sorted, the added ones are 
+ duplicate_semicolon
+ empty_return
+ eof_ending
+ function_call_space
+ include
+ object_operator
+ operators_spaces
+ remove_leading_slash_use
+ standardize_not_equal
+ ternary_spaces
+ trailing_spaces
+ whitespacy_lines

### CODE REVIEW

**Comment by Zarthus** [comment]
I personally like `else if` over `elseif`.

The rest of the rules look good to me.

**Comment by Zarthus** [comment]
lgtm

**Comment by bendem** [comment]
@kashike, @lol768, looks ok?

**Comment by lol768** [comment]
Branch needs updating, but you probably know anyway.

Do any of these rules fail on my PRs?

**Comment by bendem** [comment]
> Branch needs updating, but you probably know anyway.

It's up to date locally, not sure what's up, can always merge locally if needed.

> Do any of these rules fail on my PRs?

Nope, your PR is fine.

**Comment by lol768** [comment]
LGTM then.

**Pull request merged**
