### PR TITLE
Travis-CI

### LINKED ISSUE #199: TravisCI
Would be nice to get test results *before* merging.

### PR DESCRIPTION
**Pull request by Zarthus**
Feel free to commit on top of this.

Fixes #199

- [x] php-cs-fixer
- [x] Unit tests

### CODE REVIEW

**Comment by Zarthus** [comment]
@lol768  can you look into fixing the unit tests?

**Comment by bendem** [comment]
I know it might be a bit slower, but I don't think messing with git internal is a good solution.
We could just ask git these information like this:
```diff
diff --git a/src/Korobi/WebBundle/Util/GitInfo.php b/src/Korobi/WebBundle/Util/GitInfo.php
index 23c21f2..76782fb 100644
--- a/src/Korobi/WebBundle/Util/GitInfo.php
+++ b/src/Korobi/WebBundle/Util/GitInfo.php
@@ -25,17 +25,8 @@ class GitInfo {
      * @param string $environment
      */
     public function updateData($environment = 'dev') {
-        $root = __DIR__ . '/../../../../'; // just a bit of a hack
-        $ref = (new \SplFileObject($root . '.git/HEAD'))->getCurrentLine();
-        $ref = trim(explode(' ', $ref)[1]);
-
-        if($environment === 'prod' && file_exists($root . 'REVISION') && str_replace('refs/heads/', '', $ref) === 'deploy') {
-            $this->branch = 'www1-stable';
-            $this->hash = (new \SplFileObject($root . 'REVISION'))->getCurrentLine();
-        } else {
-            $this->branch = str_replace('refs/heads/', '', $ref);
-            $this->hash = (new \SplFileObject($root . '.git/' . $ref))->getCurrentLine();
-        }
+        $this->branch = trim(`git rev-parse --abbrev-ref HEAD`);
+        $this->hash = trim(`git rev-parse HEAD`);
     }
 
     /**
```

**Comment by lol768** [comment]
@bendem Given this is run on every request I'd like to know exactly how much time this takes compared to the previous message - I worry about the overhead of the shell, parsing the args etc etc etc

**Comment by bendem** [comment]
@lol768 git commands are around 273 times slower than reading 2 files. The last commit makes prod and staging rely on `ROOT/REVISION` to get the hash instead of using git commands which are now only used for dev (`GitInfo::updateData` takes 0.01391ms on dev, so it's not really a problem locally).

**Comment by Zarthus** [comment]
@korobi/deciders: Can we merge?

**Comment by bendem** [comment]
I'm ok with merging this, @lol768 has some concerns about `GitInfo` that can be fixed later if needed (#206).

**Pull request merged**
