### PR TITLE
Bind Mongod to 0.0.0.0

### PR DESCRIPTION
**Pull request by lol768**
@bionicrm found this issue.

### CODE REVIEW

**Comment by Zarthus** [comment]
I'm getting mixed results here:

http://docs.mongodb.org/manual/reference/configuration-options/
http://docs.mongodb.org/manual/reference/configuration-options/#net.bindIp

Are you sure the setting is bind_ip, and not bindIp?

**Comment by lol768** [comment]
That docs page only applies to the YAML configuration which we're not using:

```
vagrant@korobi-web:~/korobi-web$ cat /etc/mongod.conf 
# mongod.conf

# Where to store the data.

# Note: if you run mongodb as a non-root user (recommended) you may
# need to create and set permissions for this directory manually,
# e.g., if the parent directory isn't mutable by the mongodb user.
dbpath=/var/lib/mongodb

#where to log
logpath=/var/log/mongodb/mongod.log

logappend=true

#port = 27017

# Listen to local interface only. Comment out to listen on all interfaces. 
bind_ip = 127.0.0.1

# Disables write-ahead journaling
# nojournal = true

# Enables periodic logging of CPU utilization and I/O wait
#cpu = true

# Turn on/off security.  Off is currently the default
#noauth = true
#auth = true

# Verbose logging output.
#verbose = true

# Inspect all client data for validity on receipt (useful for
# developing drivers)
#objcheck = true

# Enable db quota management
#quota = true

# Set oplogging level where n is
#   0=off (default)
#   1=W
#   2=R
#   3=both
#   7=W+some reads
#diaglog = 0

# Ignore query hints
#nohints = true

# Enable the HTTP interface (Defaults to port 28017).
#httpinterface = true

# Turns off server-side scripting.  This will result in greatly limited
# functionality
#noscripting = true

# Turns off table scans.  Any query that would do a table scan fails.
#notablescan = true

# Disable data file preallocation.
#noprealloc = true

# Specify .ns file size for new databases.
# nssize = <size>

# Replication Options

# in replicated mongo databases, specify the replica set name here
#replSet=setname
# maximum size in megabytes for replication operation log
#oplogSize=1024
# path to a key file storing authentication info for connections
# between replica set members
#keyFile=/path/to/keyfile
vagrant@korobi-web:~/korobi-web$ 
```

I see no net.ipv6 option in the above. Regardless:

> All MongoDB programs and processes disable IPv6 support by default

**Comment by bendem** [comment]
`bind-ip` should probably be removed or changed to `[::]` instead of `0.0.0.0` to enable ipv6.

**Comment by Zarthus** [comment]
@bendem: We're trying to remove IPv6 support.

**Comment by bendem** [comment]
This changes binding from an ipv4 to another ipv4. So no ipv6 involved.
Guess I missed something. Why would you want to disable ipv6?

**Comment by Zarthus** [comment]
IIRC it was because vagrant not forwarding ipv6 making mongo unavailable

**Pull request merged**
