### PR TITLE
Fix NL's

### LINKED ISSUE #197: Line endings and .gitattributes
We need a .gitattributes file to ensure consistent line ending handling. Aim: There should be no Windows-style line-endings in the repository at all.

Files that already have windows line endings need to be fixed:

@bionicrm please fix the file you committed:

```
➜  Web git:(master) ✗ grep -IUr --color "^M" --exclude-dir=vendor

web/assets/images/flags/america.svg:<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 

web/assets/images/flags/america.svg:<polygon id="pt" points="-0.1624598481164531,0 0,-0.5 0.1624598481164531,0" transfo
web/assets/images/flags/america.svg:<g id="star"><use xlink:href="#pt" transform="rotate(-144)"/><use xlink:href="#pt" transform="rotate(-72)"/><use xlink:href="#pt"/><use xlink:href="#pt" transform="rotate(72)"/><use xlink:href="#pt" tra
web/assets/images/flags/america.svg:<g id="s5"><use xlink:href="#star" x="-0.252"/><use xlink:href="#star" x="-0.126"/>
web/assets/images/flags/america.svg:<g id="s6"><use xlink:href="#s5" x="-0.063"/><use xlink:href="#star" x="0.315"/></g
web/assets/images/flags/america.svg:<g id="x4"><use xlink:href="#s6"/><use xlink:href="#s5" y="0.054"/><use xlink:href=
web/assets/images/flags/america.svg:<g id="u"><use xlink:href="#x4" y="-0.216"/><use xlink:href="#x4"/><use xlink:href=


web/assets/images/flags/america.svg:<rect width="1235" height="650" fill="#FFF"/><use xlink:href="#stripe"/><use xlink:href="#stripe" y="100"/><use xlink:href="#stripe" y="200"/><use xlink:href="#stripe" y="300"/><use xlink:href="#stripe" y="400"/><use xlink:href="#stripe" y="500"/><use xlink:href="#stripe" y="600"/><rect width="494" height="350" fill="#3
➜  Web git:(master) ✗ 
```

### PR DESCRIPTION
**Pull request by bionicrm**
Fixes #197.

### CODE REVIEW

**Comment by Zarthus** [comment]
Do you think you can add a `.gitattributes` file to this?

https://help.github.com/articles/dealing-with-line-endings/

**Comment by lol768** [comment]
`find . -type f -exec dos2unix {} \;` seems like a good way to destroy some binary files :P

**Comment by Zarthus** [comment]
Git status will show the changes. No binaries are changed.

**Comment by lol768** [comment]
> No binaries are changed. 

```
➜  assets git:(feature/exception-responses) ✗ grep "^M" * -r                     
Binary file images/about/team/lol768.png matches
Binary file images/about/team/jamierocks.png matches
Binary file images/about/team/bendem.jpg matches
Binary file images/about/team/zarthus.jpg matches
Binary file images/about/team/kashike.jpg matches
Binary file images/stats/bar_green_v.png matches
Binary file images/stats/bar_red_v.png matches
Binary file images/stats/bar_blue_h.png matches
Binary file images/stats/bar_blue_v.png matches
Binary file images/stats/bar_red_h.png matches
Binary file images/stats/bar_green_h.png matches
Binary file images/stats/bar_yellow_h.png matches
Binary file images/stats/bar_yellow_v.png matches
Binary file images/debug_icon.png matches
Binary file images/bg.jpg matches
```

```
➜  assets git:(feature/exception-responses) ✗ find . -type f -exec echo {} \;
./css/application_application_1.css
./css/.gitkeep
./css/application.css
./js/staging_part_1.js
./js/application_part_1.js
./js/application_part_1_application_1.js
./js/application_part_1_iframeResizer.contentWindow_2.js
./js/application_part_1_prism_4.js
./js/application_part_1_iframeResizer_3.js
./js/application_part_1_prism_2.js
./js/application_part_1_prism.min_2.js
./js/application.js
./js/.gitkeep
./js/staging.js
./js/dev.js
./js/dev_part_1_dev_1.js
./images/about/team/lol768.png
./images/about/team/jamierocks.png
./images/about/team/bendem.jpg
./images/about/team/zarthus.jpg
./images/about/team/kashike.jpg
./images/.gitkeep
./images/stats/bar_green_v.png
./images/stats/bar_red_v.png
./images/stats/bar_blue_h.png
./images/stats/bar_blue_v.png
./images/stats/bar_red_h.png
./images/stats/bar_green_h.png
./images/stats/bar_yellow_h.png
./images/stats/bar_yellow_v.png
./images/debug_icon.png
./images/flags/belgium.svg
./images/flags/canada.svg
./images/flags/england.svg
./images/flags/netherlands.svg
./images/favicon.svg
./images/bg.jpg
```

Your find command matches every file, you're assuming that `dos2unix`'s binary file detection is:

a) Flawless and b) Available on the user's system (if they're running an old version it won't be there, if they're not running the version on http://waterlan.home.xs4all.nl/dos2unix.html it might not be there)

If `dos2unix`'s binary detection doesn't work, it *will* trash all of the files grep complained about in the first snippet I posted (and those are just in the assets folder).

It would be a much better idea to supply a list of acceptable file extensions to the `find` command so you're certain it's only operating on text files, though I do agree it's always a good idea to check `git status` first.

**Comment by Zarthus** [comment]
it doesn't matter if binary files get changed, you only `git add` the ones you are sure that aren't via `git status`.

**Comment by bendem** [comment]
I wonder what you're all speaking about, this fixes line endings for the repo exept bourbon (which is a vendor and should probably be converted anyway. A .gitattributes can be added with `* text=auto` so that line endings are converted automatically on checkout.

**Pull request closed without merging**
