### PR TITLE
Merge to production (changes since Sep 1st)

### PR DESCRIPTION
**Pull request by lol768**
**Important changes:**

* Addition of security page & RDP
* Redirection security fixes
* Symfony update

**Other changes:**

* Footer commit links

Would like to see this merged soon. It might be worth waiting for Travis-CI support if @Zarthus thinks it will be ready soon (assuming it's possible to predict how close it is).

### CODE REVIEW

**Comment by bendem** [comment]
https://github.com/korobi/Web/pull/204#commitcomment-13042948 hasn't been fixed yet. Has it?

**Comment by lol768** [comment]
@bendem I haven't been able to reproduce that issue myself on staging

**Comment by bendem** [comment]
Well, just click the hash in the footer, and see how it links to a non existing commit.

**Comment by Zarthus** [comment]
A temporary fix could be to hard-link to the main repository for this release and shove it off to the next merge

**Comment by kashike** [comment]
@bendem @lol768 It's s dev-only issue, happens because of silly things. I've fixed it for now

**Comment by bendem** [comment]
LGTM then.

**Comment by Zarthus** [comment]
should be mergable at this stage, yeah?

**Comment by lol768** [comment]
Now that #209 and #211 are merged in, can we get production updated/deployed with capifony @kashike?

**Pull request merged**
